### ISSUE TITLE
Strong Naming

### ISSUE THREAD

**Issue by michaelaird** [NEventStore/CommonDomain#35]
The most recently released nuget package is strongly named. The problem is that the EventStore > 4.0 is no longer strongly named. This causes much pain.

Is there any chance you could publish one last release of the nuget package that is not strongly named to alleviate this pain?

**Comment by andreabalducci** [comment]
Sorry for the delay, this project is for the old CommonDomain. Has been merged with NEventStore v5, you don't need this package for NEventStore V5.

In V6 will be splitted in a new package https://github.com/NEventStore/NEventStore.Domain to speedup development.
